//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Globalizacion {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceGymTypesResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceGymTypesResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Site.Globalizacion.ServiceGymTypesResx", typeof(ServiceGymTypesResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string HeaderDelete {
            get {
                return ResourceManager.GetString("HeaderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string HeaderDetails {
            get {
                return ResourceManager.GetString("HeaderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string HeaderEdit {
            get {
                return ResourceManager.GetString("HeaderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string HeaderType {
            get {
                return ResourceManager.GetString("HeaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver al listado.
        /// </summary>
        public static string lblBackToList {
            get {
                return ResourceManager.GetString("lblBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        public static string lblBtnCreate {
            get {
                return ResourceManager.GetString("lblBtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Tipo de Servicio.
        /// </summary>
        public static string lblBtnCreateServiceGymType {
            get {
                return ResourceManager.GetString("lblBtnCreateServiceGymType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        public static string lblDetails {
            get {
                return ResourceManager.GetString("lblDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Servicios Gimnasio.
        /// </summary>
        public static string lblTituloPageEdit {
            get {
                return ResourceManager.GetString("lblTituloPageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Tipos de Servicios.
        /// </summary>
        public static string lblTituloPagina {
            get {
                return ResourceManager.GetString("lblTituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Tipos de Servicios Gimnasio.
        /// </summary>
        public static string lblTituloPaginaCrear {
            get {
                return ResourceManager.GetString("lblTituloPaginaCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles Tipo de Servicios.
        /// </summary>
        public static string lblTituloPaginaDetalles {
            get {
                return ResourceManager.GetString("lblTituloPaginaDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Tipos de Servicios.
        /// </summary>
        public static string lblTituloPaginaEdit {
            get {
                return ResourceManager.GetString("lblTituloPaginaEdit", resourceCulture);
            }
        }
    }
}
